name: timetable
description: Customizable, animated calendar widget including day, week, and month views
version: 1.0.0-alpha.10
repository: https://github.com/JonasWanke/timetable

environment:
  sdk: '>=2.17.0-266.8.beta <3.0.0'
  flutter: '>=2.13.0-0.4.pre'

dependencies:
  async: ^2.6.0
  black_hole_flutter: ^0.3.0
  collection: ^1.15.0
  dart_date:
     git:
      url: https://github.com/xantiagoma/dart_date.git
      ref: master
  dartx: ^1.0.0
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.0
  intl: ^0.18.0
  meta: ^1.3.0
  tuple: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  glados: ^1.0.0
  test: ^1.9.4
  tuple_glados: ^1.0.0
